### ISSUE TITLE
Support timeouts

### ISSUE THREAD

**Issue by rwwagner90** [expel-io/ember-ajax-fetch#1]
jQuery has a default timeout setup for their ajax requests, but fetch does not have timeout functionality by default. We should wrap our fetch requests in a timeout handler and allow for defining custom timeout lengths.

**Comment by daochoi** [comment]
Tôi cần giảm thời gian khi lam bài thi trên web.đó cái cái timeout ,tôi ko rành về code nhưng tôi đã làm dc 1 lần và giờ ko tìm lại dc cái đoạn code đó,làm ơn chỉ dùm ạ

**Comment by rwwagner90** [comment]
Timeouts are now supported!
