### ISSUE TITLE
missing `content-type` header throws error on IE11

### ISSUE THREAD

**Issue by scottfisk** [expel-io/ember-ajax-fetch#12]
We are seeing the following error in IE11 specifically on  HTTP_204 (No Content) responses from our server:

`Unable to get property 'includes' of undefined or null reference`
It occurs on on the following line https://github.com/expel-io/ember-ajax-fetch/blob/master/addon/-private/utils/json-helpers.js#L39

In chrome and other modern browsers it appears the `content-type` header is inferred by the browser whether or not the server sends one, but IE11 does not infer it.  So the lookup https://github.com/expel-io/ember-ajax-fetch/blob/master/addon/-private/utils/json-helpers.js#L26 causes the `responseType` to be null on ie11.

On an http 204 our server does not include a `content-type` header and upon digging  into the http spec on that header it appears it is not mandatory https://stackoverflow.com/a/15860815.

I think we should probably provide a more graceful fallback for the lookup https://github.com/expel-io/ember-ajax-fetch/blob/master/addon/-private/utils/json-helpers.js#L26 here for when the header does not exist. I can probably put a PR together with just an `""` fallback or some other fallback to short circuit the `includes` check.

**Comment by rwwagner90** [comment]
@scottfisk we could put in a default of json here maybe. Not sure what the most sensible default is.

**Comment by scottfisk** [comment]
That would work for our case. Since a 204 is a success code the json case and non-json case would run basically the same code. 

Weirdly enough Chrome defaults to `text/xml` when the server does not include a `content-type` header.

**Comment by rwwagner90** [comment]
@scottfisk I'm fine with either way. Would you like to open a PR?
