### ISSUE TITLE
Shouldn't Ember-Fetch be a dependency?

### ISSUE THREAD

**Issue by webark** [expel-io/ember-ajax-fetch#9]
See it in the dev but not a regual dep.

**Comment by rwwagner90** [comment]
@webark It probably should be, but I think it isn't just to allow people to specify whatever versions they want.

**Comment by ctjhoa** [comment]
It is now
https://github.com/expel-io/ember-ajax-fetch/blob/main/package.json#L34
@rwwagner90 You can close the issue I guess

**Comment by rwwagner90** [comment]
@ctjhoa I do not have permissions to the repo anymore

**Comment by webark** [comment]
I'll close it
